/home/mburu/.local/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2024-12-09 11:52:16,712] A new study created in RDB with name: CatBoost_SAT11
[W 2024-12-09 11:52:16,978] Trial 0 failed with parameters: {'learning_rate': 0.08494024277416304, 'max_depth': 7, 'l2_leaf_reg': 13.210193406377929} because of the following error: CatBoostError("catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/SAT11/catboost_info").
Traceback (most recent call last):
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 95, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args)
  File "train.py", line 41, in cross_validation
    loss_history, val_loss_history = curr_model.fit(X_train, y_train, X_test, y_test)  # X_val, y_val)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tree_models.py", line 112, in fit
    self.model.fit(X, y, eval_set=(X_val, y_val))
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 5299, in fit
    return self._fit(X, y, cat_features, None, None, None, sample_weight, None, None, None, None, baseline,
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 2037, in _fit
    self._train(
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/SAT11/catboost_info
[W 2024-12-09 11:52:16,981] Trial 0 failed with value None.
Traceback (most recent call last):
  File "train.py", line 144, in <module>
    main(arguments)
  File "train.py", line 116, in main
    study.optimize(Objective(args, model_name, X, y), n_trials=args.n_trials)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 95, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args)
  File "train.py", line 41, in cross_validation
    loss_history, val_loss_history = curr_model.fit(X_train, y_train, X_test, y_test)  # X_val, y_val)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tree_models.py", line 112, in fit
    self.model.fit(X, y, eval_set=(X_val, y_val))
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 5299, in fit
    return self._fit(X, y, cat_features, None, None, None, sample_weight, None, None, None, None, baseline,
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 2037, in _fit
    self._train(
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/SAT11/catboost_info
srun: error: stud-000: task 0: Exited with exit code 1
[I 2024-12-09 11:52:20,422] A new study created in RDB with name: CatBoost_Diamonds
[W 2024-12-09 11:52:20,710] Trial 0 failed with parameters: {'learning_rate': 0.1344654150294894, 'max_depth': 2, 'l2_leaf_reg': 2.5556520153195783} because of the following error: CatBoostError("catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/Diamonds/catboost_info").
Traceback (most recent call last):
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 95, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args)
  File "train.py", line 41, in cross_validation
    loss_history, val_loss_history = curr_model.fit(X_train, y_train, X_test, y_test)  # X_val, y_val)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tree_models.py", line 112, in fit
    self.model.fit(X, y, eval_set=(X_val, y_val))
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 5299, in fit
    return self._fit(X, y, cat_features, None, None, None, sample_weight, None, None, None, None, baseline,
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 2037, in _fit
    self._train(
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/Diamonds/catboost_info
[W 2024-12-09 11:52:20,713] Trial 0 failed with value None.
Traceback (most recent call last):
  File "train.py", line 144, in <module>
    main(arguments)
  File "train.py", line 116, in main
    study.optimize(Objective(args, model_name, X, y), n_trials=args.n_trials)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 95, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args)
  File "train.py", line 41, in cross_validation
    loss_history, val_loss_history = curr_model.fit(X_train, y_train, X_test, y_test)  # X_val, y_val)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tree_models.py", line 112, in fit
    self.model.fit(X, y, eval_set=(X_val, y_val))
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 5299, in fit
    return self._fit(X, y, cat_features, None, None, None, sample_weight, None, None, None, None, baseline,
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 2037, in _fit
    self._train(
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/Diamonds/catboost_info
srun: error: stud-000: task 0: Exited with exit code 1
/home/mburu/.local/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2024-12-09 11:52:23,637] A new study created in RDB with name: CatBoost_House Prices Nominal
[W 2024-12-09 11:52:23,961] Trial 0 failed with parameters: {'learning_rate': 0.03781259102763196, 'max_depth': 2, 'l2_leaf_reg': 5.653144092197295} because of the following error: CatBoostError("catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/House Prices Nominal/catboost_info").
Traceback (most recent call last):
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 95, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args)
  File "train.py", line 41, in cross_validation
    loss_history, val_loss_history = curr_model.fit(X_train, y_train, X_test, y_test)  # X_val, y_val)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tree_models.py", line 112, in fit
    self.model.fit(X, y, eval_set=(X_val, y_val))
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 5299, in fit
    return self._fit(X, y, cat_features, None, None, None, sample_weight, None, None, None, None, baseline,
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 2037, in _fit
    self._train(
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/House Prices Nominal/catboost_info
[W 2024-12-09 11:52:23,964] Trial 0 failed with value None.
Traceback (most recent call last):
  File "train.py", line 144, in <module>
    main(arguments)
  File "train.py", line 116, in main
    study.optimize(Objective(args, model_name, X, y), n_trials=args.n_trials)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 95, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args)
  File "train.py", line 41, in cross_validation
    loss_history, val_loss_history = curr_model.fit(X_train, y_train, X_test, y_test)  # X_val, y_val)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tree_models.py", line 112, in fit
    self.model.fit(X, y, eval_set=(X_val, y_val))
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 5299, in fit
    return self._fit(X, y, cat_features, None, None, None, sample_weight, None, None, None, None, baseline,
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 2037, in _fit
    self._train(
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/House Prices Nominal/catboost_info
srun: error: stud-000: task 0: Exited with exit code 1
/home/mburu/.local/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2024-12-09 11:52:27,035] A new study created in RDB with name: CatBoost_Mercedes Benz
[W 2024-12-09 11:52:27,521] Trial 0 failed with parameters: {'learning_rate': 0.016816430233603928, 'max_depth': 8, 'l2_leaf_reg': 12.26123647086882} because of the following error: CatBoostError("catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/Mercedes Benz/catboost_info").
Traceback (most recent call last):
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 95, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args)
  File "train.py", line 41, in cross_validation
    loss_history, val_loss_history = curr_model.fit(X_train, y_train, X_test, y_test)  # X_val, y_val)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tree_models.py", line 112, in fit
    self.model.fit(X, y, eval_set=(X_val, y_val))
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 5299, in fit
    return self._fit(X, y, cat_features, None, None, None, sample_weight, None, None, None, None, baseline,
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 2037, in _fit
    self._train(
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/Mercedes Benz/catboost_info
[W 2024-12-09 11:52:27,523] Trial 0 failed with value None.
Traceback (most recent call last):
  File "train.py", line 144, in <module>
    main(arguments)
  File "train.py", line 116, in main
    study.optimize(Objective(args, model_name, X, y), n_trials=args.n_trials)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 95, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args)
  File "train.py", line 41, in cross_validation
    loss_history, val_loss_history = curr_model.fit(X_train, y_train, X_test, y_test)  # X_val, y_val)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tree_models.py", line 112, in fit
    self.model.fit(X, y, eval_set=(X_val, y_val))
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 5299, in fit
    return self._fit(X, y, cat_features, None, None, None, sample_weight, None, None, None, None, baseline,
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 2037, in _fit
    self._train(
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/Mercedes Benz/catboost_info
srun: error: stud-000: task 0: Exited with exit code 1
/home/mburu/.local/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2024-12-09 11:52:47,041] A new study created in RDB with name: CatBoost_Allstate Claims
[W 2024-12-09 11:53:33,969] Trial 0 failed with parameters: {'learning_rate': 0.024534696275018596, 'max_depth': 2, 'l2_leaf_reg': 9.077244935266243} because of the following error: CatBoostError("catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/Allstate Claims/catboost_info").
Traceback (most recent call last):
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 95, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args)
  File "train.py", line 41, in cross_validation
    loss_history, val_loss_history = curr_model.fit(X_train, y_train, X_test, y_test)  # X_val, y_val)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tree_models.py", line 112, in fit
    self.model.fit(X, y, eval_set=(X_val, y_val))
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 5299, in fit
    return self._fit(X, y, cat_features, None, None, None, sample_weight, None, None, None, None, baseline,
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 2037, in _fit
    self._train(
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/Allstate Claims/catboost_info
[W 2024-12-09 11:53:33,973] Trial 0 failed with value None.
Traceback (most recent call last):
  File "train.py", line 144, in <module>
    main(arguments)
  File "train.py", line 116, in main
    study.optimize(Objective(args, model_name, X, y), n_trials=args.n_trials)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 95, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args)
  File "train.py", line 41, in cross_validation
    loss_history, val_loss_history = curr_model.fit(X_train, y_train, X_test, y_test)  # X_val, y_val)
  File "/home/mburu/Master_Thesis/master-thesis-da/DNN_Trial/models/tree_models.py", line 112, in fit
    self.model.fit(X, y, eval_set=(X_val, y_val))
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 5299, in fit
    return self._fit(X, y, cat_features, None, None, None, sample_weight, None, None, None, None, baseline,
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 2037, in _fit
    self._train(
  File "/home/mburu/.local/lib/python3.8/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: output/CatBoost/Allstate Claims/catboost_info
srun: error: stud-000: task 0: Exited with exit code 1
